export const fields = {
  id: '编号',
  work: '操作',
  isUse: '使用状态',
  username: '用户名',
  petName: '昵称',
  realName: '真实姓名',
  avatar: '头像',
  password: '密码',
  affirmPassword: '确定密码',
  email: '电子邮箱',
  mobile: '手机号码',
  roles: '角色',
  introduction: '个性签名',
  isAdmin: '后台用户',
  created: '创建日期',
  createDate: '创建日期',
  aheadDate: '开始日期',
  afterDate: '结束日期',
  noAccount: '我还没有账号，去注册',
  haveAccount: '我已有账号，去登录',
  login: '登录',
  loginTitle: '管理员登录',
  register: '注册',
  registerTitle: '管理员注册',
  capsTooltip: '您输入的是大写'
}
